version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: healthy_mysql
    restart: always
    environment:
      MYSQL_DATABASE: healthy
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: healthy_user
      MYSQL_PASSWORD: healthy_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: indikamadhushan/healthy_backend:latest
    container_name: healthy_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8083:8083"
    env_file:
      - /etc/healthify/app.env
    environment:
      SERVER_PORT: 8083

volumes:
  mysql_data: