spring.application.name=personal-health-monitoring
#
#
#database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#jpa / hiberante configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


##spring.datasource.url=jdbc:mysql://localhost:3307/personal_health_monitoring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3308/indikabranch?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root


#security / jwt
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}


#file uploads
# Maximum size of a single uploaded file
spring.servlet.multipart.max-file-size=${FILE_UPLOAD_SIZE_LIMIT}

# Maximum size of the whole request
spring.servlet.multipart.max-request-size=${FILE_UPLOAD_REQUEST_SIZE_LIMIT}

#spring.jpa.hibernate.ddl-auto=create-drop


#mail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
#spring.mail.username=indikamadushan797@gmail.com
#healthify.noreply@gmail.com
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000

#contact us configuration
contact-us.to-email=${CONTACT_US_TO_EMAIL:}
contact-us.from-email=${CONTACT_US_FROM_EMAIL:}

#supabase config
supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}

supabase.bucket.profile-images=${SUPABASE_BUCKET_PROFILE_IMAGES}
supabase.bucket.doctor-verification-docs=${SUPABASE_BUCKET_DOCTOR_VERIFICATION_DOCS}
supabase.bucket.medical-files=${SUPABASE_BUCKET_MEDICAL_FILES}
